Initial commit
prjctr-imazur/gateway-service pull request #1
Opened 2022-01-16 15:20 UTC by geekartisans

2022-01-27 16:59 UTC, welikoiwanenko requested changes
Цитата из домашнего задания:
"Весь API - это принимать любой запрос, смотреть на префикс и находить в БД соответствие префикса и хост:порт для проксирования."
В БД. Не из переменных окружения. Если у тебя будет 100+ микросервисов - это 100+ переменных окружения и очень весёлая функция match в src/routes.js:38

2022-01-29 13:17 UTC, welikoiwanenko approved these changes
Токены лишние

2022-01-29 13:17 UTC, welikoiwanenko commented on .sequelizerc
> +  config: path.resolve('src', 'database', 'config.js'),
Конфиг - это не src

2022-01-29 14:37 UTC, geekartisans commented on .sequelizerc
> +  config: path.resolve('src', 'database', 'config.js'),
но это ведь конфиг для БД, который в свою очередь использует конфиг приложения

2022-01-31 11:44 UTC, welikoiwanenko commented on .sequelizerc
> +  config: path.resolve('src', 'database', 'config.js'),
src - это source code
в идеале конфиг должен лежать отдельно от сорцов

2022-01-31 13:23 UTC, closed without merging